// This file is auto-generated by @hey-api/openapi-ts

export const SDP_TaskManagement_Application_Dtos_AttachmentDtoSchema = {
  required: [
    "fileName",
    "filePath",
    "fileType",
    "formattedFileSize",
    "uploadedByUsername",
  ],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    fileName: {
      type: "string",
      nullable: true,
    },
    filePath: {
      type: "string",
      nullable: true,
    },
    fileSize: {
      type: "integer",
      format: "int64",
    },
    fileType: {
      type: "string",
      nullable: true,
    },
    uploadTime: {
      type: "string",
      format: "date-time",
    },
    taskItemId: {
      type: "integer",
      format: "int64",
    },
    uploadedById: {
      type: "integer",
      format: "int64",
    },
    uploadedByUsername: {
      type: "string",
      nullable: true,
    },
    formattedFileSize: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_BoardDtoSchema = {
  required: ["title"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    title: {
      type: "string",
      nullable: true,
    },
    description: {
      type: "string",
      nullable: true,
    },
    creationDate: {
      type: "string",
      format: "date-time",
    },
    ownerId: {
      type: "integer",
      format: "int64",
    },
    ownerName: {
      type: "string",
      nullable: true,
    },
    lists: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SDP.TaskManagement.Application.Dtos.ListDto",
      },
      nullable: true,
    },
    members: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SDP.TaskManagement.Application.Dtos.BoardMemberDto",
      },
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_BoardMemberDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    userId: {
      type: "integer",
      format: "int64",
    },
    userName: {
      type: "string",
      nullable: true,
    },
    userEmail: {
      type: "string",
      nullable: true,
    },
    userProfilePhotoPath: {
      type: "string",
      nullable: true,
    },
    boardId: {
      type: "integer",
      format: "int64",
    },
    boardName: {
      type: "string",
      nullable: true,
    },
    role: {
      $ref: "#/components/schemas/SDP.TaskManagement.Domain.Entities.BoardMemberRole",
    },
    joinedDate: {
      type: "string",
      format: "date-time",
    },
    inviterId: {
      type: "integer",
      format: "int64",
      nullable: true,
    },
    inviterName: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_ChecklistDtoSchema = {
  required: ["title"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    title: {
      type: "string",
      nullable: true,
    },
    taskItemId: {
      type: "integer",
      format: "int64",
    },
    creationDate: {
      type: "string",
      format: "date-time",
    },
    createdByUserId: {
      type: "integer",
      format: "int64",
      nullable: true,
    },
    createdByName: {
      type: "string",
      nullable: true,
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SDP.TaskManagement.Application.Dtos.ChecklistItemDto",
      },
      nullable: true,
    },
    completedItemsCount: {
      type: "integer",
      format: "int32",
      readOnly: true,
    },
    totalItemsCount: {
      type: "integer",
      format: "int32",
      readOnly: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_ChecklistItemDtoSchema = {
  required: ["content"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    content: {
      type: "string",
      nullable: true,
    },
    isChecked: {
      type: "boolean",
    },
    checklistId: {
      type: "integer",
      format: "int64",
    },
    creationDate: {
      type: "string",
      format: "date-time",
    },
    completionDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    completedByUserId: {
      type: "integer",
      format: "int64",
      nullable: true,
    },
    completedByName: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_CommentDtoSchema = {
  required: ["content", "userName"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    content: {
      type: "string",
      nullable: true,
    },
    userId: {
      type: "integer",
      format: "int64",
    },
    userName: {
      type: "string",
      nullable: true,
    },
    taskItemId: {
      type: "integer",
      format: "int64",
    },
    creationDate: {
      type: "string",
      format: "date-time",
    },
    userProfilePhotoPath: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_LabelDtoSchema = {
  required: ["color", "name"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    name: {
      type: "string",
      nullable: true,
    },
    color: {
      type: "string",
      nullable: true,
    },
    boardId: {
      type: "integer",
      format: "int64",
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_ListDtoSchema = {
  required: ["title"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    title: {
      type: "string",
      nullable: true,
    },
    boardId: {
      type: "integer",
      format: "int64",
    },
    position: {
      type: "integer",
      format: "int32",
    },
    taskItems: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SDP.TaskManagement.Application.Dtos.TaskItemDto",
      },
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_LoginDtoSchema = {
  required: ["email", "password"],
  type: "object",
  properties: {
    email: {
      type: "string",
      nullable: true,
    },
    password: {
      type: "string",
      nullable: true,
    },
    rememberMe: {
      type: "boolean",
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_MessageDtoSchema = {
  required: ["content", "recipientName", "senderName"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    senderId: {
      type: "integer",
      format: "int64",
    },
    senderName: {
      type: "string",
      nullable: true,
    },
    senderProfilePhotoPath: {
      type: "string",
      nullable: true,
    },
    recipientId: {
      type: "integer",
      format: "int64",
    },
    recipientName: {
      type: "string",
      nullable: true,
    },
    recipientProfilePhotoPath: {
      type: "string",
      nullable: true,
    },
    content: {
      type: "string",
      nullable: true,
    },
    creationDate: {
      type: "string",
      format: "date-time",
    },
    isRead: {
      type: "boolean",
    },
    readDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_NotificationDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    type: {
      $ref: "#/components/schemas/SDP.TaskManagement.Domain.Entities.NotificationType",
    },
    content: {
      type: "string",
      nullable: true,
    },
    userId: {
      type: "integer",
      format: "int64",
    },
    isRead: {
      type: "boolean",
    },
    creationDate: {
      type: "string",
      format: "date-time",
    },
    entityType: {
      type: "string",
      nullable: true,
    },
    entityId: {
      type: "integer",
      format: "int64",
      nullable: true,
    },
    actionLink: {
      type: "string",
      nullable: true,
    },
    relatedEntityType: {
      type: "string",
      nullable: true,
    },
    relatedEntityId: {
      type: "string",
      format: "uuid",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_RegisterDtoSchema = {
  required: ["email", "name", "password", "username"],
  type: "object",
  properties: {
    name: {
      type: "string",
      nullable: true,
    },
    email: {
      type: "string",
      nullable: true,
    },
    password: {
      type: "string",
      nullable: true,
    },
    username: {
      type: "string",
      nullable: true,
    },
    firstName: {
      type: "string",
      nullable: true,
    },
    lastName: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_TaskItemDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    title: {
      type: "string",
      nullable: true,
    },
    description: {
      type: "string",
      nullable: true,
    },
    dueDate: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    creationTime: {
      type: "string",
      format: "date-time",
    },
    lastModifiedTime: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    priority: {
      $ref: "#/components/schemas/SDP.TaskManagement.Domain.Entities.TaskItemPriority",
    },
    progressStatus: {
      $ref: "#/components/schemas/SDP.TaskManagement.Domain.Entities.TaskItemStatus",
    },
    ownerUserId: {
      type: "integer",
      format: "int64",
    },
    ownerUserName: {
      type: "string",
      nullable: true,
    },
    listId: {
      type: "integer",
      format: "int64",
    },
    listName: {
      type: "string",
      nullable: true,
    },
    position: {
      type: "integer",
      format: "int32",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
    assignees: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SDP.TaskManagement.Application.Dtos.UserDto",
      },
      nullable: true,
    },
    labels: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SDP.TaskManagement.Application.Dtos.LabelDto",
      },
      nullable: true,
    },
    comments: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SDP.TaskManagement.Application.Dtos.CommentDto",
      },
      nullable: true,
    },
    attachments: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SDP.TaskManagement.Application.Dtos.AttachmentDto",
      },
      nullable: true,
    },
    checklists: {
      type: "array",
      items: {
        $ref: "#/components/schemas/SDP.TaskManagement.Application.Dtos.ChecklistDto",
      },
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Application_Dtos_UserDtoSchema = {
  required: ["email", "firstName", "lastName", "username"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    username: {
      type: "string",
      nullable: true,
    },
    email: {
      type: "string",
      nullable: true,
    },
    firstName: {
      type: "string",
      nullable: true,
    },
    lastName: {
      type: "string",
      nullable: true,
    },
    profilePhotoPath: {
      type: "string",
      nullable: true,
    },
    creationDate: {
      type: "string",
      format: "date-time",
    },
    lastLogin: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    fullName: {
      type: "string",
      nullable: true,
      readOnly: true,
    },
    initials: {
      type: "string",
      nullable: true,
      readOnly: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Domain_Entities_BoardMemberRoleSchema = {
  enum: [0, 1],
  type: "integer",
  format: "int32",
} as const;

export const SDP_TaskManagement_Domain_Entities_NotificationTypeSchema = {
  enum: [0, 1, 2, 3, 4, 5],
  type: "integer",
  format: "int32",
} as const;

export const SDP_TaskManagement_Domain_Entities_TaskItemPrioritySchema = {
  enum: [0, 1, 2, 3],
  type: "integer",
  format: "int32",
} as const;

export const SDP_TaskManagement_Domain_Entities_TaskItemStatusSchema = {
  enum: [0, 1, 2, 3, 4],
  type: "integer",
  format: "int32",
} as const;

export const SDP_TaskManagement_Web_Controllers_ChangePasswordDtoSchema = {
  required: ["currentPassword", "newPassword"],
  type: "object",
  properties: {
    currentPassword: {
      type: "string",
      nullable: true,
    },
    newPassword: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Web_Controllers_DashboardStatsDtoSchema = {
  type: "object",
  properties: {
    totalTasks: {
      type: "integer",
      format: "int32",
    },
    completedTasks: {
      type: "integer",
      format: "int32",
    },
    inProgressTasks: {
      type: "integer",
      format: "int32",
    },
    todoTasks: {
      type: "integer",
      format: "int32",
    },
    overdueTasks: {
      type: "integer",
      format: "int32",
    },
    dueSoonTasks: {
      type: "integer",
      format: "int32",
    },
    highPriorityTasks: {
      type: "integer",
      format: "int32",
    },
    completionRate: {
      type: "number",
      format: "double",
    },
    totalBoards: {
      type: "integer",
      format: "int32",
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Web_Controllers_EditStatusOrPriorityInputSchema =
  {
    type: "object",
    properties: {
      progressStatus: {
        $ref: "#/components/schemas/SDP.TaskManagement.Domain.Entities.TaskItemStatus",
      },
      priority: {
        $ref: "#/components/schemas/SDP.TaskManagement.Domain.Entities.TaskItemPriority",
      },
    },
    additionalProperties: false,
  } as const;

export const SDP_TaskManagement_Web_Controllers_FilterTaskItemInputDtoSchema = {
  type: "object",
  properties: {
    title: {
      type: "string",
      nullable: true,
    },
    description: {
      type: "string",
      nullable: true,
    },
    status: {
      $ref: "#/components/schemas/SDP.TaskManagement.Domain.Entities.TaskItemStatus",
    },
    priority: {
      $ref: "#/components/schemas/SDP.TaskManagement.Domain.Entities.TaskItemPriority",
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Web_Controllers_MoveTaskDtoSchema = {
  type: "object",
  properties: {
    taskId: {
      type: "integer",
      format: "int64",
    },
    targetListId: {
      type: "integer",
      format: "int64",
    },
    position: {
      type: "integer",
      format: "int32",
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Web_Controllers_RecentActivityDtoSchema = {
  required: ["status", "title", "type"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    type: {
      type: "string",
      nullable: true,
    },
    title: {
      type: "string",
      nullable: true,
    },
    date: {
      type: "string",
      format: "date-time",
    },
    status: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Web_Controllers_ReorderListsDtoSchema = {
  type: "object",
  properties: {
    boardId: {
      type: "integer",
      format: "int64",
    },
    listIds: {
      type: "array",
      items: {
        type: "integer",
        format: "int64",
      },
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Web_Controllers_ReorderTasksDtoSchema = {
  type: "object",
  properties: {
    listId: {
      type: "integer",
      format: "int64",
    },
    taskIds: {
      type: "array",
      items: {
        type: "integer",
        format: "int64",
      },
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Web_Controllers_UpcomingTaskDtoSchema = {
  required: ["priority", "status", "title"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    title: {
      type: "string",
      nullable: true,
    },
    dueDate: {
      type: "string",
      format: "date-time",
    },
    priority: {
      type: "string",
      nullable: true,
    },
    status: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const SDP_TaskManagement_Web_Controllers_UpdateProfileDtoSchema = {
  type: "object",
  properties: {
    firstName: {
      type: "string",
      nullable: true,
    },
    lastName: {
      type: "string",
      nullable: true,
    },
    email: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;
