// This file is auto-generated by @hey-api/openapi-ts

export const LoginDtoSchema = {
  type: "object",
  properties: {
    email: {
      type: "string",
      nullable: true,
    },
    password: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const RegisterDtoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      nullable: true,
    },
    email: {
      type: "string",
      nullable: true,
    },
    password: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const TaskItemSchema = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    title: {
      type: "string",
      nullable: true,
    },
    description: {
      type: "string",
      nullable: true,
    },
    dueDate: {
      type: "string",
      format: "date-time",
    },
    creationTime: {
      type: "string",
      format: "date-time",
    },
    priority: {
      $ref: "#/components/schemas/TaskItemPriority",
    },
    progressStatus: {
      $ref: "#/components/schemas/TaskItemStatus",
    },
    ownerUser: {
      $ref: "#/components/schemas/User",
    },
    ownerUserId: {
      type: "integer",
      format: "int64",
    },
  },
  additionalProperties: false,
} as const;

export const TaskItemDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    title: {
      type: "string",
      nullable: true,
    },
    description: {
      type: "string",
      nullable: true,
    },
    dueDate: {
      type: "string",
      format: "date-time",
    },
    creationTime: {
      type: "string",
      format: "date-time",
    },
    priority: {
      $ref: "#/components/schemas/TaskItemPriority",
    },
    progressStatus: {
      $ref: "#/components/schemas/TaskItemStatus",
    },
    ownerUserId: {
      type: "integer",
      format: "int64",
    },
  },
  additionalProperties: false,
} as const;

export const TaskItemPrioritySchema = {
  enum: ["Low", "Medium", "High"],
  type: "string",
} as const;

export const TaskItemStatusSchema = {
  enum: ["Todo", "InProgress", "Completed"],
  type: "string",
} as const;

export const UserSchema = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    name: {
      type: "string",
      nullable: true,
    },
    email: {
      type: "string",
      nullable: true,
    },
    passwordHash: {
      type: "string",
      nullable: true,
    },
    ownedTaskItems: {
      type: "array",
      items: {
        $ref: "#/components/schemas/TaskItem",
      },
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const UserDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int64",
    },
    name: {
      type: "string",
      nullable: true,
    },
    email: {
      type: "string",
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;
