// This file is auto-generated by @hey-api/openapi-ts

export const LoginDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const RegisterDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const TaskItemDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string',
            nullable: true
        },
        description: {
            type: 'string',
            nullable: true
        },
        dueDate: {
            type: 'string',
            format: 'date-time'
        },
        creationTime: {
            type: 'string',
            format: 'date-time'
        },
        priority: {
            '$ref': '#/components/schemas/TaskItemPriority'
        },
        progressStatus: {
            '$ref': '#/components/schemas/TaskItemStatus'
        },
        ownerUserId: {
            type: 'string',
            format: 'uuid'
        }
    },
    additionalProperties: false
} as const;

export const TaskItemPrioritySchema = {
    enum: ['Low', 'Medium', 'High'],
    type: 'string'
} as const;

export const TaskItemStatusSchema = {
    enum: ['Todo', 'InProgress', 'Completed'],
    type: 'string'
} as const;

export const UserDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;