// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetApiTasksResponse,
  GetApiTasksByTaskItemIdResponse,
  GetApiTasksUserByUserIdResponse,
} from "./types.gen";

const userSchemaResponseTransformer = (data: any) => {
  if (data.ownedTaskItems) {
    data.ownedTaskItems = data.ownedTaskItems.map((item: any) => {
      return taskItemSchemaResponseTransformer(item);
    });
  }
  return data;
};

const taskItemSchemaResponseTransformer = (data: any) => {
  if (data.dueDate) {
    data.dueDate = new Date(data.dueDate);
  }
  if (data.creationTime) {
    data.creationTime = new Date(data.creationTime);
  }
  if (data.ownerUser) {
    data.ownerUser = userSchemaResponseTransformer(data.ownerUser);
  }
  return data;
};

export const getApiTasksResponseTransformer = async (
  data: any,
): Promise<GetApiTasksResponse> => {
  data = data.map((item: any) => {
    return taskItemSchemaResponseTransformer(item);
  });
  return data;
};

const taskItemDtoSchemaResponseTransformer = (data: any) => {
  if (data.dueDate) {
    data.dueDate = new Date(data.dueDate);
  }
  if (data.creationTime) {
    data.creationTime = new Date(data.creationTime);
  }
  return data;
};

export const getApiTasksByTaskItemIdResponseTransformer = async (
  data: any,
): Promise<GetApiTasksByTaskItemIdResponse> => {
  data = taskItemDtoSchemaResponseTransformer(data);
  return data;
};

export const getApiTasksUserByUserIdResponseTransformer = async (
  data: any,
): Promise<GetApiTasksUserByUserIdResponse> => {
  data = data.map((item: any) => {
    return taskItemSchemaResponseTransformer(item);
  });
  return data;
};
