// This file is auto-generated by @hey-api/openapi-ts

export type AttachmentDto = {
  id?: number;
  fileName: string | null;
  filePath: string | null;
  fileSize?: number;
  fileType: string | null;
  uploadTime?: Date;
  uploadUsername: string | null;
};

export type BoardCreationDto = {
  title: string | null;
  description: string | null;
  lists: Array<ListCreationDto> | null;
  boardMembers: Array<number> | null;
};

export type BoardDto = {
  id: number;
  title: string | null;
  description?: string | null;
  createdAt?: Date;
  ownerUsername: string | null;
};

export type ChangePasswordDto = {
  currentPassword: string | null;
  newPassword: string | null;
};

export type CommentDto = {
  id?: number;
  content: string | null;
  userId?: number;
  userName: string | null;
  taskItemId?: number;
  creationDate?: Date;
  userProfilePhotoPath?: string | null;
};

export type DashboardStatsDto = {
  totalTasks?: number;
  completedTasks?: number;
  inProgressTasks?: number;
  todoTasks?: number;
  overdueTasks?: number;
  dueSoonTasks?: number;
  highPriorityTasks?: number;
  completionRate?: number;
  totalBoards?: number;
};

export type EditStatusOrPriorityInput = {
  progressStatus?: TaskItemStatus;
  priority?: TaskItemPriority;
};

export type FilterTaskItemInputDto = {
  title?: string | null;
  description?: string | null;
  status?: TaskItemStatus;
  priority?: TaskItemPriority;
};

export type LabelDto = {
  id?: number;
  name: string | null;
  color: string | null;
  boardId?: number;
};

export type ListCreationDto = {
  title: string | null;
  position: number;
  boardId?: number;
};

export type ListDto = {
  id: number;
  title: string | null;
  position: number;
  taskCount: number;
};

export type LoginDto = {
  email: string | null;
  password: string | null;
  rememberMe?: boolean;
};

export type MessageDto = {
  id?: number;
  senderId?: number;
  senderName: string | null;
  senderProfilePhotoPath?: string | null;
  recipientId?: number;
  recipientName: string | null;
  recipientProfilePhotoPath?: string | null;
  content: string | null;
  creationDate?: Date;
  isRead?: boolean;
  readDate?: Date | null;
};

export type MoveTaskDto = {
  taskId?: number;
  targetListId?: number;
  position?: number;
};

export type NotificationDto = {
  id?: number;
  type?: NotificationType;
  content?: string | null;
  userId?: number;
  isRead?: boolean;
  creationDate?: Date;
  entityType?: string | null;
  entityId?: number | null;
  actionLink?: string | null;
  relatedEntityType?: string | null;
  relatedEntityId?: string | null;
};

export enum NotificationType {
  _0 = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
  _4 = 4,
  _5 = 5,
}

export type RecentActivityDto = {
  id?: number;
  type: string | null;
  title: string | null;
  date?: Date;
  status: string | null;
};

export type RegisterDto = {
  name: string | null;
  email: string | null;
  password: string | null;
  username: string | null;
  firstName?: string | null;
  lastName?: string | null;
};

export type ReorderListsDto = {
  boardId?: number;
  listIds?: Array<number> | null;
};

export type ReorderTasksDto = {
  listId?: number;
  taskIds?: Array<number> | null;
};

export type TaskItemCreationDto = {
  title: string | null;
  description?: string | null;
  dueDate?: Date | null;
  priority?: TaskItemPriority;
  progressStatus?: TaskItemStatus;
  listId?: number;
};

export type TaskItemDto = {
  id?: number;
  title: string | null;
  description?: string | null;
  dueDate?: Date | null;
  priority?: TaskItemPriority;
  progressStatus?: TaskItemStatus;
  position?: number;
  createdAt?: Date;
};

export enum TaskItemPriority {
  _0 = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
}

export enum TaskItemStatus {
  _0 = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
  _4 = 4,
}

export type UpcomingTaskDto = {
  id?: number;
  title: string | null;
  dueDate?: Date;
  priority: string | null;
  status: string | null;
};

export type UpdateProfileDto = {
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  username?: string | null;
};

export type UserDtoReadable = {
  id?: number;
  username: string | null;
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  profilePhotoPath?: string | null;
  creationDate?: Date;
  lastLogin?: Date | null;
  readonly fullName?: string | null;
  readonly initials?: string | null;
};

export type UserDtoWritable = {
  id?: number;
  username: string | null;
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  profilePhotoPath?: string | null;
  creationDate?: Date;
  lastLogin?: Date | null;
};

export type LoginData = {
  body?: LoginDto;
  path?: never;
  query?: never;
  url: "/api/Account/login";
};

export type LoginResponses = {
  /**
   * OK
   */
  200: string;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
  body?: RegisterDto;
  path?: never;
  query?: never;
  url: "/api/Account/register";
};

export type RegisterResponses = {
  /**
   * OK
   */
  200: UserDtoReadable;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type DeleteApiAttachmentByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/Attachment/{id}";
};

export type DeleteApiAttachmentByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiAttachmentByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/Attachment/{id}";
};

export type GetApiAttachmentByIdResponses = {
  /**
   * OK
   */
  200: AttachmentDto;
};

export type GetApiAttachmentByIdResponse =
  GetApiAttachmentByIdResponses[keyof GetApiAttachmentByIdResponses];

export type GetApiAttachmentTaskByTaskIdData = {
  body?: never;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/Attachment/task/{taskId}";
};

export type GetApiAttachmentTaskByTaskIdResponses = {
  /**
   * OK
   */
  200: Array<AttachmentDto>;
};

export type GetApiAttachmentTaskByTaskIdResponse =
  GetApiAttachmentTaskByTaskIdResponses[keyof GetApiAttachmentTaskByTaskIdResponses];

export type PostApiAttachmentUploadByTaskIdData = {
  body?: {
    file?: Blob | File;
  };
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/Attachment/upload/{taskId}";
};

export type PostApiAttachmentUploadByTaskIdResponses = {
  /**
   * OK
   */
  200: AttachmentDto;
};

export type PostApiAttachmentUploadByTaskIdResponse =
  PostApiAttachmentUploadByTaskIdResponses[keyof PostApiAttachmentUploadByTaskIdResponses];

export type GetApiAttachmentDownloadByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/Attachment/download/{id}";
};

export type GetApiAttachmentDownloadByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiBoardsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/boards";
};

export type GetApiBoardsResponses = {
  /**
   * OK
   */
  200: Array<BoardDto>;
};

export type GetApiBoardsResponse =
  GetApiBoardsResponses[keyof GetApiBoardsResponses];

export type PostApiBoardsData = {
  body?: BoardCreationDto;
  path?: never;
  query?: never;
  url: "/api/boards";
};

export type PostApiBoardsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteApiBoardsByBoardIdData = {
  body?: never;
  path: {
    boardId: number;
  };
  query?: never;
  url: "/api/boards/{boardId}";
};

export type DeleteApiBoardsByBoardIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiBoardsByBoardIdData = {
  body?: never;
  path: {
    boardId: number;
  };
  query?: never;
  url: "/api/boards/{boardId}";
};

export type GetApiBoardsByBoardIdResponses = {
  /**
   * OK
   */
  200: BoardDto;
};

export type GetApiBoardsByBoardIdResponse =
  GetApiBoardsByBoardIdResponses[keyof GetApiBoardsByBoardIdResponses];

export type PutApiBoardsByBoardIdData = {
  body?: BoardDto;
  path: {
    boardId: number;
  };
  query?: never;
  url: "/api/boards/{boardId}";
};

export type PutApiBoardsByBoardIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiCommentsTaskByTaskIdData = {
  body?: never;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/comments/task/{taskId}";
};

export type GetApiCommentsTaskByTaskIdResponses = {
  /**
   * OK
   */
  200: Array<CommentDto>;
};

export type GetApiCommentsTaskByTaskIdResponse =
  GetApiCommentsTaskByTaskIdResponses[keyof GetApiCommentsTaskByTaskIdResponses];

export type DeleteApiCommentsByCommentIdData = {
  body?: never;
  path: {
    commentId: number;
  };
  query?: never;
  url: "/api/comments/{commentId}";
};

export type DeleteApiCommentsByCommentIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiCommentsByCommentIdData = {
  body?: never;
  path: {
    commentId: number;
  };
  query?: never;
  url: "/api/comments/{commentId}";
};

export type GetApiCommentsByCommentIdResponses = {
  /**
   * OK
   */
  200: CommentDto;
};

export type GetApiCommentsByCommentIdResponse =
  GetApiCommentsByCommentIdResponses[keyof GetApiCommentsByCommentIdResponses];

export type PutApiCommentsByCommentIdData = {
  body?: CommentDto;
  path: {
    commentId: number;
  };
  query?: never;
  url: "/api/comments/{commentId}";
};

export type PutApiCommentsByCommentIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiCommentsData = {
  body?: CommentDto;
  path?: never;
  query?: never;
  url: "/api/comments";
};

export type PostApiCommentsResponses = {
  /**
   * OK
   */
  200: CommentDto;
};

export type PostApiCommentsResponse =
  PostApiCommentsResponses[keyof PostApiCommentsResponses];

export type GetApiDashboardStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/dashboard/stats";
};

export type GetApiDashboardStatsResponses = {
  /**
   * OK
   */
  200: DashboardStatsDto;
};

export type GetApiDashboardStatsResponse =
  GetApiDashboardStatsResponses[keyof GetApiDashboardStatsResponses];

export type GetApiDashboardRecentActivityData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/dashboard/recent-activity";
};

export type GetApiDashboardRecentActivityResponses = {
  /**
   * OK
   */
  200: Array<RecentActivityDto>;
};

export type GetApiDashboardRecentActivityResponse =
  GetApiDashboardRecentActivityResponses[keyof GetApiDashboardRecentActivityResponses];

export type GetApiDashboardUpcomingTasksData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/dashboard/upcoming-tasks";
};

export type GetApiDashboardUpcomingTasksResponses = {
  /**
   * OK
   */
  200: Array<UpcomingTaskDto>;
};

export type GetApiDashboardUpcomingTasksResponse =
  GetApiDashboardUpcomingTasksResponses[keyof GetApiDashboardUpcomingTasksResponses];

export type GetApiHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/health";
};

export type GetApiHealthResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiLabelsBoardByBoardIdData = {
  body?: never;
  path: {
    boardId: number;
  };
  query?: never;
  url: "/api/labels/board/{boardId}";
};

export type GetApiLabelsBoardByBoardIdResponses = {
  /**
   * OK
   */
  200: Array<LabelDto>;
};

export type GetApiLabelsBoardByBoardIdResponse =
  GetApiLabelsBoardByBoardIdResponses[keyof GetApiLabelsBoardByBoardIdResponses];

export type DeleteApiLabelsByLabelIdData = {
  body?: never;
  path: {
    labelId: number;
  };
  query?: never;
  url: "/api/labels/{labelId}";
};

export type DeleteApiLabelsByLabelIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiLabelsByLabelIdData = {
  body?: never;
  path: {
    labelId: number;
  };
  query?: never;
  url: "/api/labels/{labelId}";
};

export type GetApiLabelsByLabelIdResponses = {
  /**
   * OK
   */
  200: LabelDto;
};

export type GetApiLabelsByLabelIdResponse =
  GetApiLabelsByLabelIdResponses[keyof GetApiLabelsByLabelIdResponses];

export type PutApiLabelsByLabelIdData = {
  body?: LabelDto;
  path: {
    labelId: number;
  };
  query?: never;
  url: "/api/labels/{labelId}";
};

export type PutApiLabelsByLabelIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiLabelsData = {
  body?: LabelDto;
  path?: never;
  query?: never;
  url: "/api/labels";
};

export type PostApiLabelsResponses = {
  /**
   * OK
   */
  200: LabelDto;
};

export type PostApiLabelsResponse =
  PostApiLabelsResponses[keyof PostApiLabelsResponses];

export type GetApiLabelsTaskByTaskIdData = {
  body?: never;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/labels/task/{taskId}";
};

export type GetApiLabelsTaskByTaskIdResponses = {
  /**
   * OK
   */
  200: Array<LabelDto>;
};

export type GetApiLabelsTaskByTaskIdResponse =
  GetApiLabelsTaskByTaskIdResponses[keyof GetApiLabelsTaskByTaskIdResponses];

export type PostApiLabelsTaskByTaskIdAddByLabelIdData = {
  body?: never;
  path: {
    taskId: number;
    labelId: number;
  };
  query?: never;
  url: "/api/labels/task/{taskId}/add/{labelId}";
};

export type PostApiLabelsTaskByTaskIdAddByLabelIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiLabelsTaskByTaskIdRemoveByLabelIdData = {
  body?: never;
  path: {
    taskId: number;
    labelId: number;
  };
  query?: never;
  url: "/api/labels/task/{taskId}/remove/{labelId}";
};

export type PostApiLabelsTaskByTaskIdRemoveByLabelIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiListsBoardByBoardIdData = {
  body?: never;
  path: {
    boardId: number;
  };
  query?: never;
  url: "/api/lists/board/{boardId}";
};

export type GetApiListsBoardByBoardIdResponses = {
  /**
   * OK
   */
  200: Array<ListDto>;
};

export type GetApiListsBoardByBoardIdResponse =
  GetApiListsBoardByBoardIdResponses[keyof GetApiListsBoardByBoardIdResponses];

export type DeleteApiListsByListIdData = {
  body?: never;
  path: {
    listId: number;
  };
  query?: never;
  url: "/api/lists/{listId}";
};

export type DeleteApiListsByListIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiListsByListIdData = {
  body?: never;
  path: {
    listId: number;
  };
  query?: never;
  url: "/api/lists/{listId}";
};

export type GetApiListsByListIdResponses = {
  /**
   * OK
   */
  200: ListDto;
};

export type GetApiListsByListIdResponse =
  GetApiListsByListIdResponses[keyof GetApiListsByListIdResponses];

export type PutApiListsByListIdData = {
  body?: ListDto;
  path: {
    listId: number;
  };
  query?: never;
  url: "/api/lists/{listId}";
};

export type PutApiListsByListIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiListsData = {
  body?: ListCreationDto;
  path?: never;
  query?: never;
  url: "/api/lists";
};

export type PostApiListsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiListsReorderData = {
  body?: ReorderListsDto;
  path?: never;
  query?: never;
  url: "/api/lists/reorder";
};

export type PostApiListsReorderResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiMessagesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/messages";
};

export type GetApiMessagesResponses = {
  /**
   * OK
   */
  200: Array<MessageDto>;
};

export type GetApiMessagesResponse =
  GetApiMessagesResponses[keyof GetApiMessagesResponses];

export type PostApiMessagesData = {
  body?: MessageDto;
  path?: never;
  query?: never;
  url: "/api/messages";
};

export type PostApiMessagesResponses = {
  /**
   * OK
   */
  200: MessageDto;
};

export type PostApiMessagesResponse =
  PostApiMessagesResponses[keyof PostApiMessagesResponses];

export type GetApiMessagesConversationByUserIdData = {
  body?: never;
  path: {
    userId: number;
  };
  query?: never;
  url: "/api/messages/conversation/{userId}";
};

export type GetApiMessagesConversationByUserIdResponses = {
  /**
   * OK
   */
  200: Array<MessageDto>;
};

export type GetApiMessagesConversationByUserIdResponse =
  GetApiMessagesConversationByUserIdResponses[keyof GetApiMessagesConversationByUserIdResponses];

export type GetApiMessagesByMessageIdData = {
  body?: never;
  path: {
    messageId: number;
  };
  query?: never;
  url: "/api/messages/{messageId}";
};

export type GetApiMessagesByMessageIdResponses = {
  /**
   * OK
   */
  200: MessageDto;
};

export type GetApiMessagesByMessageIdResponse =
  GetApiMessagesByMessageIdResponses[keyof GetApiMessagesByMessageIdResponses];

export type PostApiMessagesByMessageIdReadData = {
  body?: never;
  path: {
    messageId: number;
  };
  query?: never;
  url: "/api/messages/{messageId}/read";
};

export type PostApiMessagesByMessageIdReadResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiNotificationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/notifications";
};

export type GetApiNotificationsResponses = {
  /**
   * OK
   */
  200: Array<NotificationDto>;
};

export type GetApiNotificationsResponse =
  GetApiNotificationsResponses[keyof GetApiNotificationsResponses];

export type GetApiNotificationsUnreadData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/notifications/unread";
};

export type GetApiNotificationsUnreadResponses = {
  /**
   * OK
   */
  200: Array<NotificationDto>;
};

export type GetApiNotificationsUnreadResponse =
  GetApiNotificationsUnreadResponses[keyof GetApiNotificationsUnreadResponses];

export type PostApiNotificationsByNotificationIdReadData = {
  body?: never;
  path: {
    notificationId: number;
  };
  query?: never;
  url: "/api/notifications/{notificationId}/read";
};

export type PostApiNotificationsByNotificationIdReadResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiNotificationsReadAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/notifications/read-all";
};

export type PostApiNotificationsReadAllResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiTasksData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/tasks";
};

export type GetApiTasksResponses = {
  /**
   * OK
   */
  200: Array<TaskItemDto>;
};

export type GetApiTasksResponse =
  GetApiTasksResponses[keyof GetApiTasksResponses];

export type PostApiTasksData = {
  body?: TaskItemCreationDto;
  path?: never;
  query?: never;
  url: "/api/tasks";
};

export type PostApiTasksResponses = {
  /**
   * OK
   */
  200: TaskItemDto;
};

export type PostApiTasksResponse =
  PostApiTasksResponses[keyof PostApiTasksResponses];

export type DeleteApiTasksByTaskIdData = {
  body?: never;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/tasks/{taskId}";
};

export type DeleteApiTasksByTaskIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiTasksByTaskIdData = {
  body?: never;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/tasks/{taskId}";
};

export type GetApiTasksByTaskIdResponses = {
  /**
   * OK
   */
  200: TaskItemDto;
};

export type GetApiTasksByTaskIdResponse =
  GetApiTasksByTaskIdResponses[keyof GetApiTasksByTaskIdResponses];

export type PutApiTasksByTaskIdData = {
  body?: TaskItemDto;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/tasks/{taskId}";
};

export type PutApiTasksByTaskIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiTasksListByListIdData = {
  body?: never;
  path: {
    listId: number;
  };
  query?: never;
  url: "/api/tasks/list/{listId}";
};

export type GetApiTasksListByListIdResponses = {
  /**
   * OK
   */
  200: Array<TaskItemDto>;
};

export type GetApiTasksListByListIdResponse =
  GetApiTasksListByListIdResponses[keyof GetApiTasksListByListIdResponses];

export type PostApiTasksMoveData = {
  body?: MoveTaskDto;
  path?: never;
  query?: never;
  url: "/api/tasks/move";
};

export type PostApiTasksMoveResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiTasksReorderData = {
  body?: ReorderTasksDto;
  path?: never;
  query?: never;
  url: "/api/tasks/reorder";
};

export type PostApiTasksReorderResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiTasksEditingByTaskItemIdData = {
  body?: EditStatusOrPriorityInput;
  path: {
    taskItemId: number;
  };
  query?: never;
  url: "/api/tasks/editing/{taskItemId}";
};

export type PutApiTasksEditingByTaskItemIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiTasksQueryingByTitlePatternData = {
  body?: never;
  path: {
    titlePattern: string;
  };
  query?: never;
  url: "/api/tasks/querying/{titlePattern}";
};

export type GetApiTasksQueryingByTitlePatternResponses = {
  /**
   * OK
   */
  200: Array<TaskItemDto>;
};

export type GetApiTasksQueryingByTitlePatternResponse =
  GetApiTasksQueryingByTitlePatternResponses[keyof GetApiTasksQueryingByTitlePatternResponses];

export type PostApiTasksQueryingData = {
  body?: FilterTaskItemInputDto;
  path?: never;
  query?: never;
  url: "/api/tasks/querying";
};

export type PostApiTasksQueryingResponses = {
  /**
   * OK
   */
  200: Array<TaskItemDto>;
};

export type PostApiTasksQueryingResponse =
  PostApiTasksQueryingResponses[keyof PostApiTasksQueryingResponses];

export type GetApiUsersProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/profile";
};

export type GetApiUsersProfileResponses = {
  /**
   * OK
   */
  200: UserDtoReadable;
};

export type GetApiUsersProfileResponse =
  GetApiUsersProfileResponses[keyof GetApiUsersProfileResponses];

export type PutApiUsersProfileData = {
  body?: UpdateProfileDto;
  path?: never;
  query?: never;
  url: "/api/users/profile";
};

export type PutApiUsersProfileResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiUsersPasswordData = {
  body?: ChangePasswordDto;
  path?: never;
  query?: never;
  url: "/api/users/password";
};

export type PutApiUsersPasswordResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiUsersSearchData = {
  body?: never;
  path?: never;
  query?: {
    query?: string;
  };
  url: "/api/users/search";
};

export type GetApiUsersSearchResponses = {
  /**
   * OK
   */
  200: Array<UserDtoReadable>;
};

export type GetApiUsersSearchResponse =
  GetApiUsersSearchResponses[keyof GetApiUsersSearchResponses];

export type GetApiUserProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/UserProfile";
};

export type GetApiUserProfileResponses = {
  /**
   * OK
   */
  200: UserDtoReadable;
};

export type GetApiUserProfileResponse =
  GetApiUserProfileResponses[keyof GetApiUserProfileResponses];

export type PutApiUserProfileData = {
  body?: UserDtoWritable;
  path?: never;
  query?: never;
  url: "/api/UserProfile";
};

export type PutApiUserProfileResponses = {
  /**
   * OK
   */
  200: UserDtoReadable;
};

export type PutApiUserProfileResponse =
  PutApiUserProfileResponses[keyof PutApiUserProfileResponses];

export type DeleteApiUserProfileProfilePhotoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/UserProfile/profile-photo";
};

export type DeleteApiUserProfileProfilePhotoResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiUserProfileProfilePhotoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/UserProfile/profile-photo";
};

export type GetApiUserProfileProfilePhotoResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiUserProfileProfilePhotoData = {
  body?: {
    file?: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/api/UserProfile/profile-photo";
};

export type PostApiUserProfileProfilePhotoResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: "http://localhost:5200" | (string & {});
};
