// This file is auto-generated by @hey-api/openapi-ts

export type LoginDto = {
  email?: string | null;
  password?: string | null;
};

export type RegisterDto = {
  name?: string | null;
  email?: string | null;
  password?: string | null;
};

export type TaskItem = {
  id?: bigint;
  title?: string | null;
  description?: string | null;
  dueDate?: Date;
  creationTime?: Date;
  priority?: TaskItemPriority;
  progressStatus?: TaskItemStatus;
  ownerUser?: User;
  ownerUserId?: bigint;
};

export type TaskItemDto = {
  id?: bigint;
  title?: string | null;
  description?: string | null;
  dueDate?: Date;
  creationTime?: Date;
  priority?: TaskItemPriority;
  progressStatus?: TaskItemStatus;
  ownerUserId?: bigint;
};

export enum TaskItemPriority {
  LOW = "Low",
  MEDIUM = "Medium",
  HIGH = "High",
}

export enum TaskItemStatus {
  TODO = "Todo",
  IN_PROGRESS = "InProgress",
  COMPLETED = "Completed",
}

export type User = {
  id?: bigint;
  name?: string | null;
  email?: string | null;
  passwordHash?: string | null;
  ownedTaskItems?: Array<TaskItem> | null;
};

export type UserDto = {
  id?: bigint;
  name?: string | null;
  email?: string | null;
};

export type LoginData = {
  body?: LoginDto;
  path?: never;
  query?: never;
  url: "/api/Account/login";
};

export type LoginResponses = {
  /**
   * OK
   */
  200: string;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
  body?: RegisterDto;
  path?: never;
  query?: never;
  url: "/api/Account/register";
};

export type RegisterResponses = {
  /**
   * OK
   */
  200: UserDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type GetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Sample";
};

export type GetUsersResponses = {
  /**
   * OK
   */
  200: Array<UserDto>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostApiTaskItemAddTaskItemData = {
  body?: TaskItemDto;
  path?: never;
  query?: never;
  url: "/api/TaskItem/AddTaskItem";
};

export type PostApiTaskItemAddTaskItemResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiTaskItemGetTaskItemByTaskItemIdData = {
  body?: never;
  path: {
    taskItemId: bigint;
  };
  query?: never;
  url: "/api/TaskItem/GetTaskItem/{taskItemId}";
};

export type GetApiTaskItemGetTaskItemByTaskItemIdResponses = {
  /**
   * OK
   */
  200: TaskItemDto;
};

export type GetApiTaskItemGetTaskItemByTaskItemIdResponse =
  GetApiTaskItemGetTaskItemByTaskItemIdResponses[keyof GetApiTaskItemGetTaskItemByTaskItemIdResponses];

export type GetApiTaskItemGetAllTaskItemsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/TaskItem/GetAllTaskItems";
};

export type GetApiTaskItemGetAllTaskItemsResponses = {
  /**
   * OK
   */
  200: Array<TaskItem>;
};

export type GetApiTaskItemGetAllTaskItemsResponse =
  GetApiTaskItemGetAllTaskItemsResponses[keyof GetApiTaskItemGetAllTaskItemsResponses];

export type GetApiTaskItemGetTaskItemByUserByUserIdData = {
  body?: never;
  path: {
    userId: bigint;
  };
  query?: never;
  url: "/api/TaskItem/GetTaskItemByUser/{userId}";
};

export type GetApiTaskItemGetTaskItemByUserByUserIdResponses = {
  /**
   * OK
   */
  200: Array<TaskItem>;
};

export type GetApiTaskItemGetTaskItemByUserByUserIdResponse =
  GetApiTaskItemGetTaskItemByUserByUserIdResponses[keyof GetApiTaskItemGetTaskItemByUserByUserIdResponses];

export type PutApiTaskItemUpdateTaskItemData = {
  body?: TaskItemDto;
  path?: never;
  query?: never;
  url: "/api/TaskItem/UpdateTaskItem";
};

export type PutApiTaskItemUpdateTaskItemResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteApiTaskItemDeleteTaskItemByTaskItemIdData = {
  body?: never;
  path: {
    taskItemId: bigint;
  };
  query?: never;
  url: "/api/TaskItem/DeleteTaskItem/{taskItemId}";
};

export type DeleteApiTaskItemDeleteTaskItemByTaskItemIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: "http://localhost:5200" | (string & {});
};
