// This file is auto-generated by @hey-api/openapi-ts

export type SdpTaskManagementApplicationDtosAttachmentDto = {
  id?: number;
  fileName: string | null;
  filePath: string | null;
  fileSize?: number;
  fileType: string | null;
  uploadTime?: Date;
  taskItemId?: number;
  uploadedById?: number;
  uploadedByUsername: string | null;
  formattedFileSize: string | null;
};

export type SdpTaskManagementApplicationDtosBoardDto = {
  id?: number;
  title: string | null;
  description?: string | null;
  creationDate?: Date;
  ownerId?: number;
  ownerName?: string | null;
  lists?: Array<SdpTaskManagementApplicationDtosListDto> | null;
  members?: Array<SdpTaskManagementApplicationDtosBoardMemberDto> | null;
};

export type SdpTaskManagementApplicationDtosBoardMemberDto = {
  id?: number;
  userId?: number;
  userName?: string | null;
  userEmail?: string | null;
  userProfilePhotoPath?: string | null;
  boardId?: number;
  boardName?: string | null;
  role?: SdpTaskManagementDomainEntitiesBoardMemberRole;
  joinedDate?: Date;
  inviterId?: number | null;
  inviterName?: string | null;
};

export type SdpTaskManagementApplicationDtosChecklistDtoReadable = {
  id?: number;
  title: string | null;
  taskItemId?: number;
  creationDate?: Date;
  createdByUserId?: number | null;
  createdByName?: string | null;
  items?: Array<SdpTaskManagementApplicationDtosChecklistItemDto> | null;
  readonly completedItemsCount?: number;
  readonly totalItemsCount?: number;
};

export type SdpTaskManagementApplicationDtosChecklistDtoWritable = {
  id?: number;
  title: string | null;
  taskItemId?: number;
  creationDate?: Date;
  createdByUserId?: number | null;
  createdByName?: string | null;
  items?: Array<SdpTaskManagementApplicationDtosChecklistItemDto> | null;
};

export type SdpTaskManagementApplicationDtosChecklistItemDto = {
  id?: number;
  content: string | null;
  isChecked?: boolean;
  checklistId?: number;
  creationDate?: Date;
  completionDate?: Date | null;
  completedByUserId?: number | null;
  completedByName?: string | null;
};

export type SdpTaskManagementApplicationDtosCommentDto = {
  id?: number;
  content: string | null;
  userId?: number;
  userName: string | null;
  taskItemId?: number;
  creationDate?: Date;
  userProfilePhotoPath?: string | null;
};

export type SdpTaskManagementApplicationDtosLabelDto = {
  id?: number;
  name: string | null;
  color: string | null;
  boardId?: number;
};

export type SdpTaskManagementApplicationDtosListDto = {
  id?: number;
  title: string | null;
  boardId?: number;
  position?: number;
  taskItems?: Array<SdpTaskManagementApplicationDtosTaskItemDto> | null;
};

export type SdpTaskManagementApplicationDtosLoginDto = {
  email: string | null;
  password: string | null;
  rememberMe?: boolean;
};

export type SdpTaskManagementApplicationDtosMessageDto = {
  id?: number;
  senderId?: number;
  senderName: string | null;
  senderProfilePhotoPath?: string | null;
  recipientId?: number;
  recipientName: string | null;
  recipientProfilePhotoPath?: string | null;
  content: string | null;
  creationDate?: Date;
  isRead?: boolean;
  readDate?: Date | null;
};

export type SdpTaskManagementApplicationDtosNotificationDto = {
  id?: number;
  type?: SdpTaskManagementDomainEntitiesNotificationType;
  content?: string | null;
  userId?: number;
  isRead?: boolean;
  creationDate?: Date;
  entityType?: string | null;
  entityId?: number | null;
  actionLink?: string | null;
  relatedEntityType?: string | null;
  relatedEntityId?: string | null;
};

export type SdpTaskManagementApplicationDtosRegisterDto = {
  name: string | null;
  email: string | null;
  password: string | null;
  username: string | null;
  firstName?: string | null;
  lastName?: string | null;
};

export type SdpTaskManagementApplicationDtosTaskItemDto = {
  id?: number;
  title?: string | null;
  description?: string | null;
  dueDate?: Date | null;
  creationTime?: Date;
  lastModifiedTime?: Date | null;
  priority?: SdpTaskManagementDomainEntitiesTaskItemPriority;
  progressStatus?: SdpTaskManagementDomainEntitiesTaskItemStatus;
  ownerUserId?: number;
  ownerUserName?: string | null;
  listId?: number;
  listName?: string | null;
  position?: number;
  createdAt?: Date;
  updatedAt?: Date;
  assignees?: Array<SdpTaskManagementApplicationDtosUserDto> | null;
  labels?: Array<SdpTaskManagementApplicationDtosLabelDto> | null;
  comments?: Array<SdpTaskManagementApplicationDtosCommentDto> | null;
  attachments?: Array<SdpTaskManagementApplicationDtosAttachmentDto> | null;
  checklists?: Array<SdpTaskManagementApplicationDtosChecklistDto> | null;
};

export type SdpTaskManagementApplicationDtosUserDtoReadable = {
  id?: number;
  username: string | null;
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  profilePhotoPath?: string | null;
  creationDate?: Date;
  lastLogin?: Date | null;
  readonly fullName?: string | null;
  readonly initials?: string | null;
};

export type SdpTaskManagementApplicationDtosUserDtoWritable = {
  id?: number;
  username: string | null;
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  profilePhotoPath?: string | null;
  creationDate?: Date;
  lastLogin?: Date | null;
};

export enum SdpTaskManagementDomainEntitiesBoardMemberRole {
  _0 = 0,
  _1 = 1,
}

export enum SdpTaskManagementDomainEntitiesNotificationType {
  _0 = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
  _4 = 4,
  _5 = 5,
}

export enum SdpTaskManagementDomainEntitiesTaskItemPriority {
  _0 = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
}

export enum SdpTaskManagementDomainEntitiesTaskItemStatus {
  _0 = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
  _4 = 4,
}

export type SdpTaskManagementWebControllersChangePasswordDto = {
  currentPassword: string | null;
  newPassword: string | null;
};

export type SdpTaskManagementWebControllersDashboardStatsDto = {
  totalTasks?: number;
  completedTasks?: number;
  inProgressTasks?: number;
  todoTasks?: number;
  overdueTasks?: number;
  dueSoonTasks?: number;
  highPriorityTasks?: number;
  completionRate?: number;
  totalBoards?: number;
};

export type SdpTaskManagementWebControllersEditStatusOrPriorityInput = {
  progressStatus?: SdpTaskManagementDomainEntitiesTaskItemStatus;
  priority?: SdpTaskManagementDomainEntitiesTaskItemPriority;
};

export type SdpTaskManagementWebControllersFilterTaskItemInputDto = {
  title?: string | null;
  description?: string | null;
  status?: SdpTaskManagementDomainEntitiesTaskItemStatus;
  priority?: SdpTaskManagementDomainEntitiesTaskItemPriority;
};

export type SdpTaskManagementWebControllersMoveTaskDto = {
  taskId?: number;
  targetListId?: number;
  position?: number;
};

export type SdpTaskManagementWebControllersRecentActivityDto = {
  id?: number;
  type: string | null;
  title: string | null;
  date?: Date;
  status: string | null;
};

export type SdpTaskManagementWebControllersReorderListsDto = {
  boardId?: number;
  listIds?: Array<number> | null;
};

export type SdpTaskManagementWebControllersReorderTasksDto = {
  listId?: number;
  taskIds?: Array<number> | null;
};

export type SdpTaskManagementWebControllersUpcomingTaskDto = {
  id?: number;
  title: string | null;
  dueDate?: Date;
  priority: string | null;
  status: string | null;
};

export type SdpTaskManagementWebControllersUpdateProfileDto = {
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
};

export type LoginData = {
  body?: SdpTaskManagementApplicationDtosLoginDto;
  path?: never;
  query?: never;
  url: "/api/Account/login";
};

export type LoginResponses = {
  /**
   * OK
   */
  200: string;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
  body?: SdpTaskManagementApplicationDtosRegisterDto;
  path?: never;
  query?: never;
  url: "/api/Account/register";
};

export type RegisterResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosUserDtoReadable;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type DeleteApiAttachmentByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/Attachment/{id}";
};

export type DeleteApiAttachmentByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiAttachmentByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/Attachment/{id}";
};

export type GetApiAttachmentByIdResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosAttachmentDto;
};

export type GetApiAttachmentByIdResponse =
  GetApiAttachmentByIdResponses[keyof GetApiAttachmentByIdResponses];

export type GetApiAttachmentTaskByTaskIdData = {
  body?: never;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/Attachment/task/{taskId}";
};

export type GetApiAttachmentTaskByTaskIdResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosAttachmentDto>;
};

export type GetApiAttachmentTaskByTaskIdResponse =
  GetApiAttachmentTaskByTaskIdResponses[keyof GetApiAttachmentTaskByTaskIdResponses];

export type PostApiAttachmentUploadByTaskIdData = {
  body?: {
    file?: Blob | File;
  };
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/Attachment/upload/{taskId}";
};

export type PostApiAttachmentUploadByTaskIdResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosAttachmentDto;
};

export type PostApiAttachmentUploadByTaskIdResponse =
  PostApiAttachmentUploadByTaskIdResponses[keyof PostApiAttachmentUploadByTaskIdResponses];

export type GetApiAttachmentDownloadByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/Attachment/download/{id}";
};

export type GetApiAttachmentDownloadByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiBoardsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/boards";
};

export type GetApiBoardsResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosBoardDto>;
};

export type GetApiBoardsResponse =
  GetApiBoardsResponses[keyof GetApiBoardsResponses];

export type PostApiBoardsData = {
  body?: SdpTaskManagementApplicationDtosBoardDto;
  path?: never;
  query?: never;
  url: "/api/boards";
};

export type PostApiBoardsResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosBoardDto;
};

export type PostApiBoardsResponse =
  PostApiBoardsResponses[keyof PostApiBoardsResponses];

export type DeleteApiBoardsByBoardIdData = {
  body?: never;
  path: {
    boardId: number;
  };
  query?: never;
  url: "/api/boards/{boardId}";
};

export type DeleteApiBoardsByBoardIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiBoardsByBoardIdData = {
  body?: never;
  path: {
    boardId: number;
  };
  query?: never;
  url: "/api/boards/{boardId}";
};

export type GetApiBoardsByBoardIdResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosBoardDto;
};

export type GetApiBoardsByBoardIdResponse =
  GetApiBoardsByBoardIdResponses[keyof GetApiBoardsByBoardIdResponses];

export type PutApiBoardsByBoardIdData = {
  body?: SdpTaskManagementApplicationDtosBoardDto;
  path: {
    boardId: number;
  };
  query?: never;
  url: "/api/boards/{boardId}";
};

export type PutApiBoardsByBoardIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiChecklistsTaskByTaskIdData = {
  body?: never;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/checklists/task/{taskId}";
};

export type GetApiChecklistsTaskByTaskIdResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosChecklistDtoReadable>;
};

export type GetApiChecklistsTaskByTaskIdResponse =
  GetApiChecklistsTaskByTaskIdResponses[keyof GetApiChecklistsTaskByTaskIdResponses];

export type DeleteApiChecklistsByChecklistIdData = {
  body?: never;
  path: {
    checklistId: number;
  };
  query?: never;
  url: "/api/checklists/{checklistId}";
};

export type DeleteApiChecklistsByChecklistIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiChecklistsByChecklistIdData = {
  body?: never;
  path: {
    checklistId: number;
  };
  query?: never;
  url: "/api/checklists/{checklistId}";
};

export type GetApiChecklistsByChecklistIdResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosChecklistDtoReadable;
};

export type GetApiChecklistsByChecklistIdResponse =
  GetApiChecklistsByChecklistIdResponses[keyof GetApiChecklistsByChecklistIdResponses];

export type PutApiChecklistsByChecklistIdData = {
  body?: SdpTaskManagementApplicationDtosChecklistDtoWritable;
  path: {
    checklistId: number;
  };
  query?: never;
  url: "/api/checklists/{checklistId}";
};

export type PutApiChecklistsByChecklistIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiChecklistsData = {
  body?: SdpTaskManagementApplicationDtosChecklistDtoWritable;
  path?: never;
  query?: never;
  url: "/api/checklists";
};

export type PostApiChecklistsResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosChecklistDtoReadable;
};

export type PostApiChecklistsResponse =
  PostApiChecklistsResponses[keyof PostApiChecklistsResponses];

export type PostApiChecklistsItemsData = {
  body?: SdpTaskManagementApplicationDtosChecklistItemDto;
  path?: never;
  query?: never;
  url: "/api/checklists/items";
};

export type PostApiChecklistsItemsResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosChecklistItemDto;
};

export type PostApiChecklistsItemsResponse =
  PostApiChecklistsItemsResponses[keyof PostApiChecklistsItemsResponses];

export type DeleteApiChecklistsItemsByItemIdData = {
  body?: never;
  path: {
    itemId: number;
  };
  query?: never;
  url: "/api/checklists/items/{itemId}";
};

export type DeleteApiChecklistsItemsByItemIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiChecklistsItemsByItemIdData = {
  body?: never;
  path: {
    itemId: number;
  };
  query?: never;
  url: "/api/checklists/items/{itemId}";
};

export type GetApiChecklistsItemsByItemIdResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosChecklistItemDto;
};

export type GetApiChecklistsItemsByItemIdResponse =
  GetApiChecklistsItemsByItemIdResponses[keyof GetApiChecklistsItemsByItemIdResponses];

export type PutApiChecklistsItemsByItemIdData = {
  body?: SdpTaskManagementApplicationDtosChecklistItemDto;
  path: {
    itemId: number;
  };
  query?: never;
  url: "/api/checklists/items/{itemId}";
};

export type PutApiChecklistsItemsByItemIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiCommentsTaskByTaskIdData = {
  body?: never;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/comments/task/{taskId}";
};

export type GetApiCommentsTaskByTaskIdResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosCommentDto>;
};

export type GetApiCommentsTaskByTaskIdResponse =
  GetApiCommentsTaskByTaskIdResponses[keyof GetApiCommentsTaskByTaskIdResponses];

export type DeleteApiCommentsByCommentIdData = {
  body?: never;
  path: {
    commentId: number;
  };
  query?: never;
  url: "/api/comments/{commentId}";
};

export type DeleteApiCommentsByCommentIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiCommentsByCommentIdData = {
  body?: never;
  path: {
    commentId: number;
  };
  query?: never;
  url: "/api/comments/{commentId}";
};

export type GetApiCommentsByCommentIdResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosCommentDto;
};

export type GetApiCommentsByCommentIdResponse =
  GetApiCommentsByCommentIdResponses[keyof GetApiCommentsByCommentIdResponses];

export type PutApiCommentsByCommentIdData = {
  body?: SdpTaskManagementApplicationDtosCommentDto;
  path: {
    commentId: number;
  };
  query?: never;
  url: "/api/comments/{commentId}";
};

export type PutApiCommentsByCommentIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiCommentsData = {
  body?: SdpTaskManagementApplicationDtosCommentDto;
  path?: never;
  query?: never;
  url: "/api/comments";
};

export type PostApiCommentsResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosCommentDto;
};

export type PostApiCommentsResponse =
  PostApiCommentsResponses[keyof PostApiCommentsResponses];

export type GetApiDashboardStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/dashboard/stats";
};

export type GetApiDashboardStatsResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementWebControllersDashboardStatsDto;
};

export type GetApiDashboardStatsResponse =
  GetApiDashboardStatsResponses[keyof GetApiDashboardStatsResponses];

export type GetApiDashboardRecentActivityData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/dashboard/recent-activity";
};

export type GetApiDashboardRecentActivityResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementWebControllersRecentActivityDto>;
};

export type GetApiDashboardRecentActivityResponse =
  GetApiDashboardRecentActivityResponses[keyof GetApiDashboardRecentActivityResponses];

export type GetApiDashboardUpcomingTasksData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/dashboard/upcoming-tasks";
};

export type GetApiDashboardUpcomingTasksResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementWebControllersUpcomingTaskDto>;
};

export type GetApiDashboardUpcomingTasksResponse =
  GetApiDashboardUpcomingTasksResponses[keyof GetApiDashboardUpcomingTasksResponses];

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/Health";
};

export type GetHealthResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/health";
};

export type GetApiHealthResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiLabelsBoardByBoardIdData = {
  body?: never;
  path: {
    boardId: number;
  };
  query?: never;
  url: "/api/labels/board/{boardId}";
};

export type GetApiLabelsBoardByBoardIdResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosLabelDto>;
};

export type GetApiLabelsBoardByBoardIdResponse =
  GetApiLabelsBoardByBoardIdResponses[keyof GetApiLabelsBoardByBoardIdResponses];

export type DeleteApiLabelsByLabelIdData = {
  body?: never;
  path: {
    labelId: number;
  };
  query?: never;
  url: "/api/labels/{labelId}";
};

export type DeleteApiLabelsByLabelIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiLabelsByLabelIdData = {
  body?: never;
  path: {
    labelId: number;
  };
  query?: never;
  url: "/api/labels/{labelId}";
};

export type GetApiLabelsByLabelIdResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosLabelDto;
};

export type GetApiLabelsByLabelIdResponse =
  GetApiLabelsByLabelIdResponses[keyof GetApiLabelsByLabelIdResponses];

export type PutApiLabelsByLabelIdData = {
  body?: SdpTaskManagementApplicationDtosLabelDto;
  path: {
    labelId: number;
  };
  query?: never;
  url: "/api/labels/{labelId}";
};

export type PutApiLabelsByLabelIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiLabelsData = {
  body?: SdpTaskManagementApplicationDtosLabelDto;
  path?: never;
  query?: never;
  url: "/api/labels";
};

export type PostApiLabelsResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosLabelDto;
};

export type PostApiLabelsResponse =
  PostApiLabelsResponses[keyof PostApiLabelsResponses];

export type PostApiLabelsTaskByTaskIdAddByLabelIdData = {
  body?: never;
  path: {
    taskId: number;
    labelId: number;
  };
  query?: never;
  url: "/api/labels/task/{taskId}/add/{labelId}";
};

export type PostApiLabelsTaskByTaskIdAddByLabelIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiLabelsTaskByTaskIdRemoveByLabelIdData = {
  body?: never;
  path: {
    taskId: number;
    labelId: number;
  };
  query?: never;
  url: "/api/labels/task/{taskId}/remove/{labelId}";
};

export type PostApiLabelsTaskByTaskIdRemoveByLabelIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiListsBoardByBoardIdData = {
  body?: never;
  path: {
    boardId: number;
  };
  query?: never;
  url: "/api/lists/board/{boardId}";
};

export type GetApiListsBoardByBoardIdResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosListDto>;
};

export type GetApiListsBoardByBoardIdResponse =
  GetApiListsBoardByBoardIdResponses[keyof GetApiListsBoardByBoardIdResponses];

export type DeleteApiListsByListIdData = {
  body?: never;
  path: {
    listId: number;
  };
  query?: never;
  url: "/api/lists/{listId}";
};

export type DeleteApiListsByListIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiListsByListIdData = {
  body?: never;
  path: {
    listId: number;
  };
  query?: never;
  url: "/api/lists/{listId}";
};

export type GetApiListsByListIdResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosListDto;
};

export type GetApiListsByListIdResponse =
  GetApiListsByListIdResponses[keyof GetApiListsByListIdResponses];

export type PutApiListsByListIdData = {
  body?: SdpTaskManagementApplicationDtosListDto;
  path: {
    listId: number;
  };
  query?: never;
  url: "/api/lists/{listId}";
};

export type PutApiListsByListIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiListsData = {
  body?: SdpTaskManagementApplicationDtosListDto;
  path?: never;
  query?: never;
  url: "/api/lists";
};

export type PostApiListsResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosListDto;
};

export type PostApiListsResponse =
  PostApiListsResponses[keyof PostApiListsResponses];

export type PostApiListsReorderData = {
  body?: SdpTaskManagementWebControllersReorderListsDto;
  path?: never;
  query?: never;
  url: "/api/lists/reorder";
};

export type PostApiListsReorderResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiMessagesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/messages";
};

export type GetApiMessagesResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosMessageDto>;
};

export type GetApiMessagesResponse =
  GetApiMessagesResponses[keyof GetApiMessagesResponses];

export type PostApiMessagesData = {
  body?: SdpTaskManagementApplicationDtosMessageDto;
  path?: never;
  query?: never;
  url: "/api/messages";
};

export type PostApiMessagesResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosMessageDto;
};

export type PostApiMessagesResponse =
  PostApiMessagesResponses[keyof PostApiMessagesResponses];

export type GetApiMessagesConversationByUserIdData = {
  body?: never;
  path: {
    userId: number;
  };
  query?: never;
  url: "/api/messages/conversation/{userId}";
};

export type GetApiMessagesConversationByUserIdResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosMessageDto>;
};

export type GetApiMessagesConversationByUserIdResponse =
  GetApiMessagesConversationByUserIdResponses[keyof GetApiMessagesConversationByUserIdResponses];

export type GetApiMessagesByMessageIdData = {
  body?: never;
  path: {
    messageId: number;
  };
  query?: never;
  url: "/api/messages/{messageId}";
};

export type GetApiMessagesByMessageIdResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosMessageDto;
};

export type GetApiMessagesByMessageIdResponse =
  GetApiMessagesByMessageIdResponses[keyof GetApiMessagesByMessageIdResponses];

export type PostApiMessagesByMessageIdReadData = {
  body?: never;
  path: {
    messageId: number;
  };
  query?: never;
  url: "/api/messages/{messageId}/read";
};

export type PostApiMessagesByMessageIdReadResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiNotificationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/notifications";
};

export type GetApiNotificationsResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosNotificationDto>;
};

export type GetApiNotificationsResponse =
  GetApiNotificationsResponses[keyof GetApiNotificationsResponses];

export type GetApiNotificationsUnreadData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/notifications/unread";
};

export type GetApiNotificationsUnreadResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosNotificationDto>;
};

export type GetApiNotificationsUnreadResponse =
  GetApiNotificationsUnreadResponses[keyof GetApiNotificationsUnreadResponses];

export type PostApiNotificationsByNotificationIdReadData = {
  body?: never;
  path: {
    notificationId: number;
  };
  query?: never;
  url: "/api/notifications/{notificationId}/read";
};

export type PostApiNotificationsByNotificationIdReadResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiNotificationsReadAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/notifications/read-all";
};

export type PostApiNotificationsReadAllResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiSampleGetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Sample/GetUsers";
};

export type GetApiSampleGetUsersResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosUserDtoReadable>;
};

export type GetApiSampleGetUsersResponse =
  GetApiSampleGetUsersResponses[keyof GetApiSampleGetUsersResponses];

export type GetApiTasksData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/tasks";
};

export type GetApiTasksResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosTaskItemDto>;
};

export type GetApiTasksResponse =
  GetApiTasksResponses[keyof GetApiTasksResponses];

export type PostApiTasksData = {
  body?: SdpTaskManagementApplicationDtosTaskItemDto;
  path?: never;
  query?: never;
  url: "/api/tasks";
};

export type PostApiTasksResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosTaskItemDto;
};

export type PostApiTasksResponse =
  PostApiTasksResponses[keyof PostApiTasksResponses];

export type DeleteApiTasksByTaskIdData = {
  body?: never;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/tasks/{taskId}";
};

export type DeleteApiTasksByTaskIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiTasksByTaskIdData = {
  body?: never;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/tasks/{taskId}";
};

export type GetApiTasksByTaskIdResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosTaskItemDto;
};

export type GetApiTasksByTaskIdResponse =
  GetApiTasksByTaskIdResponses[keyof GetApiTasksByTaskIdResponses];

export type PutApiTasksByTaskIdData = {
  body?: SdpTaskManagementApplicationDtosTaskItemDto;
  path: {
    taskId: number;
  };
  query?: never;
  url: "/api/tasks/{taskId}";
};

export type PutApiTasksByTaskIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiTasksListByListIdData = {
  body?: never;
  path: {
    listId: number;
  };
  query?: never;
  url: "/api/tasks/list/{listId}";
};

export type GetApiTasksListByListIdResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosTaskItemDto>;
};

export type GetApiTasksListByListIdResponse =
  GetApiTasksListByListIdResponses[keyof GetApiTasksListByListIdResponses];

export type PostApiTasksMoveData = {
  body?: SdpTaskManagementWebControllersMoveTaskDto;
  path?: never;
  query?: never;
  url: "/api/tasks/move";
};

export type PostApiTasksMoveResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiTasksReorderData = {
  body?: SdpTaskManagementWebControllersReorderTasksDto;
  path?: never;
  query?: never;
  url: "/api/tasks/reorder";
};

export type PostApiTasksReorderResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiTasksEditingByTaskItemIdData = {
  body?: SdpTaskManagementWebControllersEditStatusOrPriorityInput;
  path: {
    taskItemId: number;
  };
  query?: never;
  url: "/api/tasks/editing/{taskItemId}";
};

export type PutApiTasksEditingByTaskItemIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiTasksQueryingByTitlePatternData = {
  body?: never;
  path: {
    titlePattern: string;
  };
  query?: never;
  url: "/api/tasks/querying/{titlePattern}";
};

export type GetApiTasksQueryingByTitlePatternResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosTaskItemDto>;
};

export type GetApiTasksQueryingByTitlePatternResponse =
  GetApiTasksQueryingByTitlePatternResponses[keyof GetApiTasksQueryingByTitlePatternResponses];

export type PostApiTasksQueryingData = {
  body?: SdpTaskManagementWebControllersFilterTaskItemInputDto;
  path?: never;
  query?: never;
  url: "/api/tasks/querying";
};

export type PostApiTasksQueryingResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosTaskItemDto>;
};

export type PostApiTasksQueryingResponse =
  PostApiTasksQueryingResponses[keyof PostApiTasksQueryingResponses];

export type GetApiUsersProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/profile";
};

export type GetApiUsersProfileResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosUserDtoReadable;
};

export type GetApiUsersProfileResponse =
  GetApiUsersProfileResponses[keyof GetApiUsersProfileResponses];

export type PutApiUsersProfileData = {
  body?: SdpTaskManagementWebControllersUpdateProfileDto;
  path?: never;
  query?: never;
  url: "/api/users/profile";
};

export type PutApiUsersProfileResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiUsersPasswordData = {
  body?: SdpTaskManagementWebControllersChangePasswordDto;
  path?: never;
  query?: never;
  url: "/api/users/password";
};

export type PutApiUsersPasswordResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiUsersSearchData = {
  body?: never;
  path?: never;
  query?: {
    query?: string;
  };
  url: "/api/users/search";
};

export type GetApiUsersSearchResponses = {
  /**
   * OK
   */
  200: Array<SdpTaskManagementApplicationDtosUserDtoReadable>;
};

export type GetApiUsersSearchResponse =
  GetApiUsersSearchResponses[keyof GetApiUsersSearchResponses];

export type GetApiUserProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/UserProfile";
};

export type GetApiUserProfileResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosUserDtoReadable;
};

export type GetApiUserProfileResponse =
  GetApiUserProfileResponses[keyof GetApiUserProfileResponses];

export type PutApiUserProfileData = {
  body?: SdpTaskManagementApplicationDtosUserDtoWritable;
  path?: never;
  query?: never;
  url: "/api/UserProfile";
};

export type PutApiUserProfileResponses = {
  /**
   * OK
   */
  200: SdpTaskManagementApplicationDtosUserDtoReadable;
};

export type PutApiUserProfileResponse =
  PutApiUserProfileResponses[keyof PutApiUserProfileResponses];

export type DeleteApiUserProfileProfilePhotoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/UserProfile/profile-photo";
};

export type DeleteApiUserProfileProfilePhotoResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiUserProfileProfilePhotoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/UserProfile/profile-photo";
};

export type GetApiUserProfileProfilePhotoResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiUserProfileProfilePhotoData = {
  body?: {
    file?: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/api/UserProfile/profile-photo";
};

export type PostApiUserProfileProfilePhotoResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: "http://localhost:7200" | (string & {});
};
